apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: greetapp-rollout
  namespace: testing
  labels:
    app: greetapp-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greetapp-rollout
  template:
    metadata:
      labels:
        app: greetapp-rollout
    spec:
      containers:
        - name: greet-app
          resources: {}
          image: greet-app@sha256:fe91de6203d7f91997cf85003502336929de0621214d20fae37b16a7372add93
          env:
            - name: appVersion
              value: v9
          ports:
            - name: m-pod-metrics
              containerPort: 8080
  strategy:
    canary:
      maxSurge: 2
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: greetapp
  namespace: testing
  labels:
    app: greetapp
spec:
  type: ClusterIP
  selector:
    app: greetapp-rollout
  ports:
    - name: https
      port: 7001
      targetPort: 8080
