apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-integrations-manager
  namespace: bank-integration
  labels:
    app.kubernetes.io/name: bank-integrations-manager
    app: bank-integrations-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bank-integrations-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bank-integrations-manager
        app: bank-integrations-manager
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "9101"
        proxy.istio.io/config: |
          terminationDrainDuration: 300s
          holdApplicationUntilProxyStarts: true
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
      terminationGracePeriodSeconds: 30
      containers:
        - name: bank-integrations-manager
          imagePullPolicy: IfNotPresent
          image: bim-local:v7.0.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: logback_appenders
              value: json
            - name: application_cached-secret-max-lifetime
              value: 60m
            - name: application_bank-integration-cached-secret-max-lifetime
              value: 60m
            - name: application_docker-image
              value: bank-integrations
            - name: application_shutdown-delay-millis
              value: '3000'
            - name: spring_lifecycle_timeout-per-shutdown-phase
              value: '1m'
            - name: logging_level_com_trustly_bankintegrationsmanager
              value: "DEBUG"
            - name: integration-selector_get-integration-url
              value: "http://192.168.49.2:8282/selector/v1/integration"# This host might need be change. run-> 'minikube ssh' then run->'cat /etc/hosts' to find correct host
            - name: bank-integrations_defaultHost
              value: "http://bank-integrations.bank-integration/command"
            - name: bank-integrations_devDispatcherHost
              value: "http://bank-integrations.bank-integration/command"
            - name: redis_host
              value: "192.168.49.2" # This host might need be change. run-> 'minikube ssh' then run->'cat /etc/hosts' to find correct host
            - name: management.server.port
              value: '9101'
            - name: server.port
              value: '8080'
            - name: spring_profiles_include
              value: dev, kafka_off
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9101
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9101
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9101
              scheme: HTTP
            failureThreshold: 60
            periodSeconds: 15
            timeoutSeconds: 5
