apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bain-api
  namespace: bank-integration
spec:
  hosts:
    - bain-api
  http:
    - name: bim-routes
      match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 80
            host: bank-integrations-manager.bank-integration
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: bain-api-service-entry
spec:
  hosts:
    - bain-api.bank-integration
  location: MESH_INTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
