apiVersion: v1
kind: Service
metadata:
  name: bain-api
  labels:
    app.kubernetes.io/name: bank-integrations-manager
spec:
  ports:
    - name: http
      port: 80
      targetPort: 443
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bain-api-virtual-service
  namespace: bank-integration
spec:
  hosts:
    - bain-api
  http:
    - name: "first-call"
      match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 80
            host: bank-integrations-manager
            headers:
              request:
                add:
                  X-Forwarded-Client-Cert: "{request.headers['original-client-cert']}"
