apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bain-api
  namespace: bank-integration
spec:
  hosts:
    - bain-api
  http:
    - name: bim-routes
      match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 80
            host: bank-integrations-manager.bank-integration
