apiVersion: v1
kind: Service
metadata:
  name: bain-api
  namespace: bank-integration
  labels:
    app.kubernetes.io/name: bank-integrations-manager
spec:
  ports:
    - name: http
      port: 80
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: bank-integrations-manager
    app: bank-integrations-manager

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bain-api-virtual-service
  namespace: bank-integration
spec:
  hosts:
    - bain-api
  http:
    - name: bim-routes
      match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 80
            host: bank-integrations-manager.bank-integration
