apiVersion: v1
kind: Service
metadata:
  name: bain-api
  labels:
    app.kubernetes.io/name: bank-integrations-manager
spec:
  ports:
    - name: http
      port: 80
      targetPort: 443
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bain-api-virtual-service
  namespace: bank-integration
spec:
  hosts:
    - bain-api
  http:
    - name: "first-call"
      match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 80
            host: bank-integrations-manager
      filters:
        - name: envoy.filters.http.lua
          config:
            inlineCode: |
              function envoy_on_request(request_handle)
                -- Extract the value from the original-client-cert header
                local original_cert = request_handle:headers():get("original-client-cert")
                if original_cert then
                  -- Set the value of X-Forwarded-Client-Cert header
                  request_handle:headers():replace("X-Forwarded-Client-Cert", original_cert)
                end
              end
