apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-job-manager
  namespace: bank-integration
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-job-manager-binding
  namespace: bank-integration
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-job-manager
---
