apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bank-integration-gw
  namespace: istio-test
spec:
  selector:
    istio: ingressgateway
    app: istio-ingressgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - bain-integration.com
