apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: greetapp-rollout
  namespace: localdevelopment
  labels:
    app: greetapp-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greetapp-rollout
  template:
    metadata:
      labels:
        app: greetapp-rollout
    spec:
      containers:
        - name: greet-app
          resources: {}
          image: dockerbishalthapa/greet-app@sha256:aeb328d4811575671f16549ca20a1d3cefe356c941569abfb85fc339349d2a7b
          env:
            - name: appVersion
              value: v9
          ports:
            - name: m-pod-metrics
              containerPort: 8080
  strategy:
    canary:
      maxSurge: 2
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: greetapp
  namespace: localdevelopment
  labels:
    app: greetapp
spec:
  type: ClusterIP
  selector:
    app: greetapp-rollout
  ports:
    - name: https
      port: 7001
      targetPort: 8080
