apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bank-integrations
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: bank-integrations
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50
