apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "peer-policy"
  namespace: bank-integration
spec:
  selector:
    matchLabels:
      app: bank-integrations
  portLevelMtls:
    80:
      mode: DISABLE

---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: auth-policy
  namespace: bank-integration
spec:
  selector:
    matchLabels:
      app: bank-integrations
  action: ALLOW
  rules:
    - from:
      - source:
          principals: ["*"]
    - to:
        - operation:
            methods: ["GET", "HEAD", "POST", "PUT"]
            ports: ["80", "8080"]
