apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: bank-integration
spec:
  rules:
    - {}

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "workload-policy"
  namespace: bank-integration
spec:
  selector:
    matchLabels:
      app: bank-integrations
  portLevelMtls:
    80:
      mode: DISABLE
