apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankintegration-ingress
  namespace: bank-integration
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  ingressClassName: istio
  rules:
    - host: bain-integration.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: bank-integrations
                port:
                  number: 80
