apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bain-api-proxy
  namespace: bank-integration
  labels:
    app.kubernetes.io/name: bain-api-proxy
    app: bain-api-proxy
spec:
  strategy:
    canary:
      maxUnavailable: 1
      steps:
        - setWeight: 50
        - pause: { duration: 3m }
        - setWeight: 100
        - pause: { duration: 30m }
  selector:
    matchLabels:
      app.kubernetes.io/name: bain-api-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bain-api-proxy
        app: bain-api-proxy
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
      terminationGracePeriodSeconds: 120
      containers:
        - name: bain-api-proxy
          imagePullPolicy: IfNotPresent
          image: nginx-preview-proxy:local
          ports:
            - containerPort: 8080
              name: http
          env:
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            failureThreshold: 60
            periodSeconds: 15
            timeoutSeconds: 5
