apiVersion: batch/v1
kind: CronJob
metadata:
  name: move-swish-report
  namespace: bank-integration
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: bain-api-preview
          restartPolicy: OnFailure
          containers:
            - name: cron-job-process-s3-report
              image: public.ecr.aws/aws-cli/aws-cli:2.22.4
              imagePullPolicy: IfNotPresent
              command: [ "/bin/bash", "/scripts/process_s3_report.sh" ]
              env:
                - name: SWISH_REPORT_PA_ENDPOINT
                  value: "http://swish-report.product/report/api/v1/processing-accounts?partnerBank=Northmill"
                - name: S3_BANK_INTEGRATION_BUCKET
                  value: "trustly-490093413857-eu-west-1-sftp-bank-integration/northmill"
                - name: S3_REPORTS_BUCKET
                  value: "s3://trustly-490093413857-eu-west-1-sftp-swish-reports"
                - name: S3_ARCHIVE_BUCKET
                  value: "s3://trustly-490093413857-eu-west-1-sftp-swish-reports/swish-archive"
              volumeMounts:
                - name: move-swish-report-script
                  mountPath: /scripts
          volumes:
            - name: move-swish-report-script
              configMap:
                name: process-s3-script
      backoffLimit: 1
