apiVersion: v1
kind: ConfigMap
metadata:
  name: process-s3-script
  namespace: bank-integration
data:
  process_s3_report.sh: |
   curl -s https://5976f2c5-1393-43fc-8d78-52679a94c03a.mock.pstmn.io/api/v1/processing-account | grep -E '"processingAccountName"|"partnerBankIban"' | \
   awk -F': ' '{gsub(/"|,/, "", $2); print $2}' | \
   paste - - |
   while read key value; do
     processingAccountName=$key
     partnerBankIban=$value
     maskedPartnerBankIban="${partnerBankIban:0:4}********************${partnerBankIban: -6}"
     echo "Processing account: $processingAccountName with IBAN: $maskedPartnerBankIban"
   done
