apiVersion: v1
kind: ConfigMap
metadata:
  name: process-s3-script
  namespace: bank-integration
data:
  process_s3_report.sh: |
    
    # Fetch the response from the API
    northmill_accounts=$(curl -v "$SWIH_REPORT_ENDPOINT")
    if [ -z "$northmill_accounts" ]; then
      echo "Failed to fetch API response. Exiting." >&2
      exit 1
    fi
    
    echo $northmill_accounts
