apiVersion: v1
kind: ServiceAccount
metadata:
  name: bain-api-preview
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bain-api-preview-cluster-role
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
      - namespaces
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  bain-api-preview-cluster-role-binding
  namespace: bank-integration
subjects:
  - kind: ServiceAccount
    name: bain-api-preview
    namespace: bank-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bain-api-preview-cluster-role
